version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  groups:
    pip-dependencies:
      patterns:
        - "*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  groups:
    github-actions:
      patterns:
        - "*"