version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: grpcio
    versions:
    - 1.35.0
    - 1.36.0
  - dependency-name: pyfakefs
    versions:
    - 4.3.3
