@echo off
IF "%GAUGE_PYTHON_COMMAND%"=="" (SET GAUGE_PYTHON_COMMAND=python)

REM Resolve relative paths against the project root
IF "%GAUGE_PROJECT_ROOT%"=="" GOTO :run
IF "%GAUGE_PYTHON_COMMAND:~1,1%"==":" GOTO :run
SETLOCAL ENABLEDELAYEDEXPANSION
SET "_CMD=!GAUGE_PYTHON_COMMAND!"
SET "_STRIPPED=!_CMD:\=!"
SET "_STRIPPED=!_STRIPPED:/=!"
IF "!_STRIPPED!"=="!_CMD!" (
  ENDLOCAL
  GOTO :run
)
ENDLOCAL
SET "GAUGE_PYTHON_COMMAND=%GAUGE_PROJECT_ROOT%\%GAUGE_PYTHON_COMMAND%"

:run
"%GAUGE_PYTHON_COMMAND%" check_and_install_getgauge.py
"%GAUGE_PYTHON_COMMAND%" -u start.py %1
