# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lsp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import getgauge.messages.messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lsp.proto',
  package='gauge.messages',
  syntax='proto3',
  serialized_options=_b('\n\026com.thoughtworks.gauge\252\002\016Gauge.Messages'),
  serialized_pb=_b('\n\tlsp.proto\x12\x0egauge.messages\x1a\x0emessages.proto2\x9c\x07\n\nlspService\x12X\n\x0cGetStepNames\x12 .gauge.messages.StepNamesRequest\x1a!.gauge.messages.StepNamesResponse\"\x03\x88\x02\x01\x12I\n\tCacheFile\x12 .gauge.messages.CacheFileRequest\x1a\x15.gauge.messages.Empty\"\x03\x88\x02\x01\x12\x64\n\x10GetStepPositions\x12$.gauge.messages.StepPositionsRequest\x1a%.gauge.messages.StepPositionsResponse\"\x03\x88\x02\x01\x12\x64\n\x16GetImplementationFiles\x12\x15.gauge.messages.Empty\x1a..gauge.messages.ImplementationFileListResponse\"\x03\x88\x02\x01\x12]\n\rImplementStub\x12-.gauge.messages.StubImplementationCodeRequest\x1a\x18.gauge.messages.FileDiff\"\x03\x88\x02\x01\x12^\n\x0cValidateStep\x12#.gauge.messages.StepValidateRequest\x1a$.gauge.messages.StepValidateResponse\"\x03\x88\x02\x01\x12R\n\x08Refactor\x12\x1f.gauge.messages.RefactorRequest\x1a .gauge.messages.RefactorResponse\"\x03\x88\x02\x01\x12U\n\x0bGetStepName\x12\x1f.gauge.messages.StepNameRequest\x1a .gauge.messages.StepNameResponse\"\x03\x88\x02\x01\x12\x64\n\x0fGetGlobPatterns\x12\x15.gauge.messages.Empty\x1a\x35.gauge.messages.ImplementationFileGlobPatternResponse\"\x03\x88\x02\x01\x12M\n\x0bKillProcess\x12\".gauge.messages.KillProcessRequest\x1a\x15.gauge.messages.Empty\"\x03\x88\x02\x01\x42)\n\x16\x63om.thoughtworks.gauge\xaa\x02\x0eGauge.Messagesb\x06proto3')
  ,
  dependencies=[messages__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_LSPSERVICE = _descriptor.ServiceDescriptor(
  name='lspService',
  full_name='gauge.messages.lspService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=46,
  serialized_end=970,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStepNames',
    full_name='gauge.messages.lspService.GetStepNames',
    index=0,
    containing_service=None,
    input_type=messages__pb2._STEPNAMESREQUEST,
    output_type=messages__pb2._STEPNAMESRESPONSE,
    serialized_options=_b('\210\002\001'),
  ),
  _descriptor.MethodDescriptor(
    name='CacheFile',
    full_name='gauge.messages.lspService.CacheFile',
    index=1,
    containing_service=None,
    input_type=messages__pb2._CACHEFILEREQUEST,
    output_type=messages__pb2._EMPTY,
    serialized_options=_b('\210\002\001'),
  ),
  _descriptor.MethodDescriptor(
    name='GetStepPositions',
    full_name='gauge.messages.lspService.GetStepPositions',
    index=2,
    containing_service=None,
    input_type=messages__pb2._STEPPOSITIONSREQUEST,
    output_type=messages__pb2._STEPPOSITIONSRESPONSE,
    serialized_options=_b('\210\002\001'),
  ),
  _descriptor.MethodDescriptor(
    name='GetImplementationFiles',
    full_name='gauge.messages.lspService.GetImplementationFiles',
    index=3,
    containing_service=None,
    input_type=messages__pb2._EMPTY,
    output_type=messages__pb2._IMPLEMENTATIONFILELISTRESPONSE,
    serialized_options=_b('\210\002\001'),
  ),
  _descriptor.MethodDescriptor(
    name='ImplementStub',
    full_name='gauge.messages.lspService.ImplementStub',
    index=4,
    containing_service=None,
    input_type=messages__pb2._STUBIMPLEMENTATIONCODEREQUEST,
    output_type=messages__pb2._FILEDIFF,
    serialized_options=_b('\210\002\001'),
  ),
  _descriptor.MethodDescriptor(
    name='ValidateStep',
    full_name='gauge.messages.lspService.ValidateStep',
    index=5,
    containing_service=None,
    input_type=messages__pb2._STEPVALIDATEREQUEST,
    output_type=messages__pb2._STEPVALIDATERESPONSE,
    serialized_options=_b('\210\002\001'),
  ),
  _descriptor.MethodDescriptor(
    name='Refactor',
    full_name='gauge.messages.lspService.Refactor',
    index=6,
    containing_service=None,
    input_type=messages__pb2._REFACTORREQUEST,
    output_type=messages__pb2._REFACTORRESPONSE,
    serialized_options=_b('\210\002\001'),
  ),
  _descriptor.MethodDescriptor(
    name='GetStepName',
    full_name='gauge.messages.lspService.GetStepName',
    index=7,
    containing_service=None,
    input_type=messages__pb2._STEPNAMEREQUEST,
    output_type=messages__pb2._STEPNAMERESPONSE,
    serialized_options=_b('\210\002\001'),
  ),
  _descriptor.MethodDescriptor(
    name='GetGlobPatterns',
    full_name='gauge.messages.lspService.GetGlobPatterns',
    index=8,
    containing_service=None,
    input_type=messages__pb2._EMPTY,
    output_type=messages__pb2._IMPLEMENTATIONFILEGLOBPATTERNRESPONSE,
    serialized_options=_b('\210\002\001'),
  ),
  _descriptor.MethodDescriptor(
    name='KillProcess',
    full_name='gauge.messages.lspService.KillProcess',
    index=9,
    containing_service=None,
    input_type=messages__pb2._KILLPROCESSREQUEST,
    output_type=messages__pb2._EMPTY,
    serialized_options=_b('\210\002\001'),
  ),
])
_sym_db.RegisterServiceDescriptor(_LSPSERVICE)

DESCRIPTOR.services_by_name['lspService'] = _LSPSERVICE

# @@protoc_insertion_point(module_scope)
